### ISSUE TITLE
aether clobbers d3.

### ISSUE THREAD

**Issue by Hypercubed** [codecombat/aether#136] opened 2015-01-27 11:55 UTC
Is it known that aether clobbers d3?  Anyway around it... short of running in a webworker?

Here is a plunker: http://plnkr.co/edit/Fs6DDK?p=info

**Comment by nwinter** [comment] 2015-01-27 13:03
Hmm, sorry about that; we always run it in a web worker. It's gotten pretty aggressive with how much it tries to protect builtins and disable unsafe accesses and things like this. I've just played around with it for a little while, but I haven't yet found out what's going wrong. I did find that the clobbering doesn't happen until `aether.run(method);`.

Curious: what do you want to use Aether for?

**Comment by Hypercubed** [comment] 2015-01-27 14:44
Yes, I discovered that too.  Interestingly if you fail to include lodash you will get the same error but the trouble begins at `new Aether(aetherOptions)` instead.

**Comment by Hypercubed** [comment] 2015-01-29 02:49
The clobbering happens on the first call to `copyBuiltin` function inside `module.exports.restoreBuiltins` which tries to restore a copy of `Object`.  The "real" `Object` returned after this call does not have the correct prototype.

`module.exports.restoreBuiltins`  is called from `module.exports.wrapWithSandbox` even if protectAPI is false.

So maybe this is two bugs:

1) `module.exports.restoreBuiltins` should not be called if protectAPI === false.
2) `Object` is not restored correctly.

**Comment by nwinter** [comment] 2015-02-03 20:45
Part of this was fixed in #138. Now, I guess the issue is just that `Object.__proto__` isn't being restored correctly in this case.

**Comment by nwinter** [comment] 2016-05-22 15:39
Should be fixed with @basicer's new Esper interpreter, as we no longer run any of the code which messed with protecting builtins.

**Closed by nwinter** 2016-05-22 15:39 UTC
Labels: bug
